### ISSUE TITLE
Traefik instance freeze

### ISSUE THREAD

**Issue by lfache** [containous/plugin-simplecache#4]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Launch simple-cache plugin :) 

### What did you expect to see?

Make a simple docker-compose with : 

```yaml 
version: '3.8'
services:
  traefik:
    image: traefik:2.3
    restart: unless-stopped
    command:
      --api.insecure=true
      --accesslog
      --log.level=DEBUG
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --entrypoints.websecure.http.tls.certresolver=myresolver
      --entrypoints.web.http.redirections.entryPoint.to=:443
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --providers.docker
      --providers.docker.exposedbydefault=false
      --certificatesresolvers.myresolver.acme.tlschallenge
      --certificatesresolvers.myresolver.acme.email=foo@you.com
      --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      --experimental.pilot.token=xxxx
      --experimental.plugins.cache.modulename=github.com/containous/plugin-simplecache
      --experimental.plugins.cache.version=v0.1.0
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Admin port
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt
    networks:
      - web

  whoami:
    image: containous/whoami
    labels:
      traefik.enable: true
      traefik.docker.network: web
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: 'Host(`${URL}`)'
      traefik.http.services.whoami.loadbalancer.server.port: 80
      #traefik.http.middlewares.my-plugin-cache.plugin.cache.path: "/tmp/"
      #traefik.http.routers.whoami.middlewares: 'my-plugin-cache' 
    networks:
      - web

volumes:
  certs:

networks:
  web:
    name: traefik_wan

```
Launch Traefik and It is freezing even by not activating the plugin on my instance. Problem of interpreting?

### What did you see instead?

Works :)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0-rc2
Codename:     picodon
Go version:   go1.14.5
Built:        2020-07-15T20:22:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```
